server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址

        #需要注意的是uri的协议为lb,表示启用GateWay的负载均衡功能
        #lb://serviceName是spring cloud gateway在微服务中自动创建的负载均衡uri
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
#            - After=2021-09-10T14:47:41.493+08:00[Asia/Shanghai]
#            - Cookie=username,zzj
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Host=**.org.example
#            - Method=GET
#            - Query=username, \d+ #要有参数名称并且是正整数才能路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka
